<?php

namespace Database\Seeders;

use App\Models\Game;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        $games = [
            [
                'title' => 'Elden Ring',
                'slug' => 'elden-ring',
                'description' => 'Traverse the shattered Lands Between, uncover ancient mysteries, and forge your own path to become the Elden Lord.',
                'genre' => 'Action RPG',
                'developer' => 'FromSoftware',
                'publisher' => 'Bandai Namco Entertainment',
                'release_date' => '2022-02-25',
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#b8860b',
                'initials' => 'ER',
            ],
            [
                'title' => 'Cyberpunk 2077',
                'slug' => 'cyberpunk-2077',
                'description' => 'An open-world RPG set in the neon-drenched sprawl of Night City.',
                'genre' => 'Open World RPG',
                'developer' => 'CD Projekt Red',
                'publisher' => 'CD Projekt',
                'release_date' => '2020-12-10',
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#d4a017',
                'initials' => 'CP',
            ],
            [
                'title' => 'God of War',
                'slug' => 'god-of-war',
                'description' => 'Kratos and Atreus journey through the treacherous Norse realms.',
                'genre' => 'Action Adventure',
                'developer' => 'Santa Monica Studio',
                'publisher' => 'Sony Interactive Entertainment',
                'release_date' => '2018-04-20',
                'platforms' => ['PC', 'PS5'],
                'color' => '#9b2335',
                'initials' => 'GW',
            ],
            [
                'title' => 'The Last of Us Part II',
                'slug' => 'the-last-of-us-part-ii',
                'description' => 'A story of love, loss, and the cycle of vengeance.',
                'genre' => 'Survival Horror',
                'developer' => 'Naughty Dog',
                'publisher' => 'Sony Interactive Entertainment',
                'release_date' => '2020-06-19',
                'platforms' => ['PC', 'PS5'],
                'color' => '#2d6a4f',
                'initials' => 'LO',
            ],
            [
                'title' => 'Hollow Knight',
                'slug' => 'hollow-knight',
                'description' => 'Descend into Hallownest, a vast underground kingdom of bugs and ancient secrets.',
                'genre' => 'Metroidvania',
                'developer' => 'Team Cherry',
                'publisher' => 'Team Cherry',
                'release_date' => '2017-02-24',
                'platforms' => ['PC', 'PS5', 'Xbox', 'Switch'],
                'color' => '#4e5b9e',
                'initials' => 'HK',
            ],
            [
                'title' => "Baldur's Gate 3",
                'slug' => 'baldurs-gate-3',
                'description' => 'A choice-driven party RPG set in the Forgotten Realms.',
                'genre' => 'RPG',
                'developer' => 'Larian Studios',
                'publisher' => 'Larian Studios',
                'release_date' => '2023-08-03',
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#6b2fa0',
                'initials' => 'BG',
            ],
            [
                'title' => 'Hades',
                'slug' => 'hades',
                'description' => 'Fight out of the Underworld as Zagreus in a story-rich roguelite.',
                'genre' => 'Roguelite',
                'developer' => 'Supergiant Games',
                'publisher' => 'Supergiant Games',
                'release_date' => '2020-09-17',
                'platforms' => ['PC', 'PS5', 'Xbox', 'Switch'],
                'color' => '#c0392b',
                'initials' => 'HD',
            ],
            [
                'title' => 'Stardew Valley',
                'slug' => 'stardew-valley',
                'description' => 'Restore a farm and build a new life in Pelican Town.',
                'genre' => 'Simulation',
                'developer' => 'ConcernedApe',
                'publisher' => 'ConcernedApe',
                'release_date' => '2016-02-26',
                'platforms' => ['PC', 'PS5', 'Xbox', 'Switch'],
                'color' => '#27ae60',
                'initials' => 'SV',
            ],
            [
                'title' => 'Disco Elysium',
                'slug' => 'disco-elysium',
                'description' => 'A detective RPG built around conversation, thought, and consequence.',
                'genre' => 'RPG',
                'developer' => 'ZA/UM',
                'publisher' => 'ZA/UM',
                'release_date' => '2019-10-15',
                'platforms' => ['PC', 'PS5', 'Xbox', 'Switch'],
                'color' => '#2980b9',
                'initials' => 'DE',
            ],
            [
                'title' => 'Sekiro: Shadows Die Twice',
                'slug' => 'sekiro-shadows-die-twice',
                'description' => 'A precision-driven action adventure in late Sengoku Japan.',
                'genre' => 'Action RPG',
                'developer' => 'FromSoftware',
                'publisher' => 'Activision',
                'release_date' => '2019-03-22',
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#636363',
                'initials' => 'SK',
            ],
            [
                'title' => 'Red Dead Redemption 2',
                'slug' => 'red-dead-redemption-2',
                'description' => 'A sweeping American epic set at the twilight of the outlaw era.',
                'genre' => 'Open World',
                'developer' => 'Rockstar Games',
                'publisher' => 'Rockstar Games',
                'release_date' => '2018-10-26',
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#7d3c2a',
                'initials' => 'RD',
            ],
            [
                'title' => 'Dark Souls III',
                'slug' => 'dark-souls-iii',
                'description' => 'Journey through decaying kingdoms and face the lords of cinder.',
                'genre' => 'Action RPG',
                'developer' => 'FromSoftware',
                'publisher' => 'Bandai Namco Entertainment',
                'release_date' => '2016-03-24',
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#3d3d3d',
                'initials' => 'DS',
            ],
            [
                'title' => 'Monster Hunter: World',
                'slug' => 'monster-hunter-world',
                'description' => 'Track and hunt magnificent creatures across living ecosystems.',
                'genre' => 'Action RPG',
                'developer' => 'Capcom',
                'publisher' => 'Capcom',
                'release_date' => '2018-01-26',
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#c0622a',
                'initials' => 'MH',
            ],
            [
                'title' => 'The Witcher 3',
                'slug' => 'the-witcher-3',
                'description' => 'Geralt of Rivia searches war-ravaged lands for Ciri.',
                'genre' => 'Open World RPG',
                'developer' => 'CD Projekt Red',
                'publisher' => 'CD Projekt',
                'release_date' => '2015-05-19',
                'platforms' => ['PC', 'PS5', 'Xbox', 'Switch'],
                'color' => '#2c5f2e',
                'initials' => 'W3',
            ],
            [
                'title' => 'Ghost of Tsushima',
                'slug' => 'ghost-of-tsushima',
                'description' => 'Forge a new path beyond the samurai code to liberate Tsushima.',
                'genre' => 'Action Adventure',
                'developer' => 'Sucker Punch Productions',
                'publisher' => 'Sony Interactive Entertainment',
                'release_date' => '2020-07-17',
                'platforms' => ['PC', 'PS5'],
                'color' => '#1a4a6e',
                'initials' => 'GT',
            ],
            [
                'title' => 'Echoes of Aether',
                'slug' => 'echoes-of-aether',
                'description' => 'A future action RPG included as local development seed data.',
                'genre' => 'Action RPG',
                'developer' => 'Northstar Studio',
                'publisher' => 'Northstar Studio',
                'release_date' => now()->addMonths(3)->toDateString(),
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#4a7c6f',
                'initials' => 'EA',
            ],
            [
                'title' => 'Neon Divide',
                'slug' => 'neon-divide',
                'description' => 'A future co-op shooter included as local development seed data.',
                'genre' => 'FPS',
                'developer' => 'Signal Arc',
                'publisher' => 'Signal Arc',
                'release_date' => now()->addMonths(6)->toDateString(),
                'platforms' => ['PC', 'Xbox'],
                'color' => '#8b4088',
                'initials' => 'ND',
            ],
            [
                'title' => 'Kingdoms Beyond',
                'slug' => 'kingdoms-beyond',
                'description' => 'A future role-playing game included as local development seed data.',
                'genre' => 'RPG',
                'developer' => 'Cinder Works',
                'publisher' => 'Cinder Works',
                'release_date' => now()->addMonths(9)->toDateString(),
                'platforms' => ['PC', 'PS5'],
                'color' => '#5a3e7c',
                'initials' => 'KB',
            ],
            [
                'title' => 'Wildfront',
                'slug' => 'wildfront',
                'description' => 'A future open-world adventure included as local development seed data.',
                'genre' => 'Open World',
                'developer' => 'Juniper Games',
                'publisher' => 'Juniper Games',
                'release_date' => now()->addYear()->toDateString(),
                'platforms' => ['PC', 'PS5', 'Xbox'],
                'color' => '#a0522d',
                'initials' => 'WF',
            ],
            [
                'title' => 'Silken Path',
                'slug' => 'silken-path',
                'description' => 'A future metroidvania included as local development seed data.',
                'genre' => 'Metroidvania',
                'developer' => 'Mothlight',
                'publisher' => 'Mothlight',
                'release_date' => now()->addMonths(15)->toDateString(),
                'platforms' => ['PC', 'Switch'],
                'color' => '#3d4f8a',
                'initials' => 'SP',
            ],
        ];

        foreach ($games as $game) {
            Game::create($game);
        }
    }
}
